// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doi_gia.sql

package sqlcgen

import (
	"context"
)

const doiGia = `-- name: DoiGia :one
UPDATE menu_component SET base_price_vnd = $2 WHERE id = $1
RETURNING id, base_price_vnd
`

type DoiGiaParams struct {
	ID           int64
	BasePriceVnd int64
}

type DoiGiaRow struct {
	ID           int64
	BasePriceVnd int64
}

// Cửa menu/doi_gia_thanh_phan (P3-06, lớp chu_quan); người và lý do đã khai trong giao dịch.
func (q *Queries) DoiGia(ctx context.Context, arg DoiGiaParams) (DoiGiaRow, error) {
	row := q.db.QueryRow(ctx, doiGia, arg.ID, arg.BasePriceVnd)
	var i DoiGiaRow
	err := row.Scan(&i.ID, &i.BasePriceVnd)
	return i, err
}
