// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doi_phu_thu.sql

package sqlcgen

import (
	"context"
)

const doiPhuThu = `-- name: DoiPhuThu :one
UPDATE menu_option SET surcharge_vnd = $2 WHERE id = $1
RETURNING id, surcharge_vnd
`

type DoiPhuThuParams struct {
	ID           int64
	SurchargeVnd int64
}

type DoiPhuThuRow struct {
	ID           int64
	SurchargeVnd int64
}

// Cửa menu/doi_phu_thu (P3-06, lớp chu_quan); người và lý do đã khai trong giao dịch.
func (q *Queries) DoiPhuThu(ctx context.Context, arg DoiPhuThuParams) (DoiPhuThuRow, error) {
	row := q.db.QueryRow(ctx, doiPhuThu, arg.ID, arg.SurchargeVnd)
	var i DoiPhuThuRow
	err := row.Scan(&i.ID, &i.SurchargeVnd)
	return i, err
}
