// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: khai_ly_do.sql

package sqlcgen

import (
	"context"
)

const khaiLyDo = `-- name: KhaiLyDo :exec
SELECT set_config('shop.revision_reason', $1, true)
`

// Khai lý do sửa cho vết của giao dịch này (I-018); trigger ghi vết đọc shop.revision_reason.
func (q *Queries) KhaiLyDo(ctx context.Context, setConfig string) error {
	_, err := q.db.Exec(ctx, khaiLyDo, setConfig)
	return err
}
