// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: khoa_mon_ngung_ban.sql

package sqlcgen

import (
	"context"
)

const khoaMonNgungBan = `-- name: KhoaMonNgungBan :one
SELECT (discontinued_at IS NOT NULL)::boolean AS da_ngung FROM menu_item WHERE id = $1 FOR UPDATE
`

// Khoá dòng món và đọc đã có mốc ngừng bán chưa; ép ::boolean để sqlc sinh bool, không interface{}.
func (q *Queries) KhoaMonNgungBan(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, khoaMonNgungBan, id)
	var da_ngung bool
	err := row.Scan(&da_ngung)
	return da_ngung, err
}
