// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: khoa_mon_thanh_phan.sql

package sqlcgen

import (
	"context"
)

const khoaMonThanhPhan = `-- name: KhoaMonThanhPhan :one
SELECT id FROM menu_item_component WHERE menu_item_id = $1 AND menu_component_id = $2 FOR UPDATE
`

type KhoaMonThanhPhanParams struct {
	MenuItemID      int64
	MenuComponentID int64
}

// Khoá đúng cặp món · thành phần trước khi sửa số lượng; không có dòng ⇒ menu_item_component_not_found.
func (q *Queries) KhoaMonThanhPhan(ctx context.Context, arg KhoaMonThanhPhanParams) (int64, error) {
	row := q.db.QueryRow(ctx, khoaMonThanhPhan, arg.MenuItemID, arg.MenuComponentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
