// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: khoa_thanh_phan.sql

package sqlcgen

import (
	"context"
)

const khoaThanhPhan = `-- name: KhoaThanhPhan :one
SELECT id FROM menu_component WHERE id = $1 FOR UPDATE
`

// Khoá dòng thành phần trước khi đổi giá; không có dòng ⇒ menu_component_not_found.
func (q *Queries) KhoaThanhPhan(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, khoaThanhPhan, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
