// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: khoa_lua_chon.sql

package sqlcgen

import (
	"context"
)

const khoaLuaChon = `-- name: KhoaLuaChon :one
SELECT id FROM menu_option WHERE id = $1 FOR UPDATE
`

// Khoá dòng lựa chọn trước khi đổi phụ thu; không có dòng ⇒ menu_option_not_found.
func (q *Queries) KhoaLuaChon(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, khoaLuaChon, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
