// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceDay struct {
	ID                  int64
	WorkerPersonID      int64
	WorkDate            pgtype.Date
	PersonID            int64
	CreatedAt           pgtype.Timestamptz
	CancelledAt         pgtype.Timestamptz
	CancelledByPersonID pgtype.Int8
	CancelNote          pgtype.Text
}

type Bill struct {
	ID                 int64
	TableSessionID     pgtype.Int8
	SalesOrderID       pgtype.Int8
	DueVnd             int64
	CashVnd            int64
	TransferVnd        int64
	PrepaidCashVnd     int64
	PrepaidTransferVnd int64
	DebtVnd            int64
	DebtorName         pgtype.Text
	IDIfPrepaid        pgtype.Int8
	BookedAt           pgtype.Timestamptz
	SaleDate           pgtype.Date
	CreatedAt          pgtype.Timestamptz
	PersonID           int64
	PaperLedgerID      pgtype.Int8
	PaperEntryCount    pgtype.Int4
	PaperPosition      pgtype.Int4
	DebtNote           pgtype.Text
}

type CashCount struct {
	ID        int64
	SaleDate  pgtype.Date
	PersonID  int64
	CreatedAt pgtype.Timestamptz
}

type CashCountLine struct {
	ID              int64
	CashCountID     int64
	DenominationVnd int64
	AmountVnd       int64
	CreatedAt       pgtype.Timestamptz
}

type CounterDuty struct {
	ID        int64
	PersonID  int64
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type DebtCollection struct {
	ID                 int64
	BillID             int64
	DebtVnd            int64
	CashVnd            int64
	TransferVnd        int64
	BookedAt           pgtype.Timestamptz
	SaleDate           pgtype.Date
	CreatedAt          pgtype.Timestamptz
	PersonID           int64
	RemainingBeforeVnd pgtype.Int8
	RemainingVnd       int64
}

type DiningTable struct {
	ID        int64
	Label     string
	CreatedAt pgtype.Timestamptz
}

type HolidayBonu struct {
	ID             int64
	WorkerPersonID int64
	AmountVnd      int64
	PaidDate       pgtype.Date
	PersonID       int64
	CreatedAt      pgtype.Timestamptz
}

type MenuComponent struct {
	ID           int64
	Name         string
	BasePriceVnd int64
	TakesFilling bool
	CreatedAt    pgtype.Timestamptz
}

type MenuComponentStation struct {
	ID              int64
	MenuComponentID int64
	StationCode     string
	CreatedAt       pgtype.Timestamptz
}

type MenuItem struct {
	ID             int64
	Name           string
	DiscontinuedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type MenuItemComponent struct {
	ID              int64
	MenuItemID      int64
	MenuComponentID int64
	Quantity        int32
	CreatedAt       pgtype.Timestamptz
}

type MenuItemOptionGroup struct {
	ID            int64
	MenuItemID    int64
	OptionGroupID int64
	CreatedAt     pgtype.Timestamptz
}

type MenuOption struct {
	ID            int64
	OptionGroupID int64
	Name          string
	SurchargeVnd  int64
	CreatedAt     pgtype.Timestamptz
}

type OpeningFloat struct {
	ID        int64
	SaleDate  pgtype.Date
	CreatedAt pgtype.Timestamptz
	PersonID  int64
}

type OpeningFloatLine struct {
	ID              int64
	OpeningFloatID  int64
	DenominationVnd int64
	AmountVnd       int64
	CreatedAt       pgtype.Timestamptz
}

type OptionGroup struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OptionGroupPrerequisite struct {
	ID            int64
	OptionGroupID int64
	MenuOptionID  int64
	CreatedAt     pgtype.Timestamptz
}

type OrderIntakePause struct {
	ID                int64
	StartedAt         pgtype.Timestamptz
	StartedByPersonID int64
	EndedAt           pgtype.Timestamptz
	EndedByPersonID   pgtype.Int8
	CreatedAt         pgtype.Timestamptz
}

type OrderLine struct {
	ID             int64
	SalesOrderID   int64
	Quantity       int32
	IsTakeaway     bool
	CreatedAt      pgtype.Timestamptz
	MenuItemID     int64
	ItemName       string
	UnitPriceVnd   int64
	LineTotalVnd   pgtype.Int8
	PricedAt       pgtype.Timestamptz
	ComponentCount int32
}

type OrderLineComponent struct {
	ID                 int64
	OrderLineID        int64
	Position           int32
	LineComponentCount int32
	PreviousPosition   pgtype.Int4
	MenuComponentID    int64
	ComponentName      string
	Quantity           int32
	TakesFilling       bool
	BasePriceVnd       int64
	CreatedAt          pgtype.Timestamptz
}

type OrderLineOption struct {
	ID              int64
	OrderLineID     int64
	MenuOptionID    int64
	OptionGroupName string
	OptionName      string
	SurchargeVnd    int64
	CreatedAt       pgtype.Timestamptz
}

type PaperLedger struct {
	ID         int64
	SaleDate   pgtype.Date
	EntryCount int32
	PersonID   int64
	DeclaredAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Person struct {
	ID          int64
	DisplayName string
	IsOwner     bool
	CreatedAt   pgtype.Timestamptz
}

type Prepayment struct {
	ID           int64
	SalesOrderID int64
	CashVnd      int64
	TransferVnd  int64
	BookedAt     pgtype.Timestamptz
	SaleDate     pgtype.Date
	CreatedAt    pgtype.Timestamptz
	PersonID     int64
}

type PrepaymentUse struct {
	ID                int64
	PrepaymentID      int64
	SalesOrderID      int64
	UseNo             int32
	CashBeforeVnd     int64
	TransferBeforeVnd int64
	TakeCashVnd       int64
	TakeTransferVnd   int64
	CashAfterVnd      pgtype.Int8
	TransferAfterVnd  pgtype.Int8
	TakeVnd           pgtype.Int8
	FirstPrepaymentID pgtype.Int8
	PreviousUseNo     pgtype.Int4
	BillID            pgtype.Int8
	RefundID          pgtype.Int8
	CreatedAt         pgtype.Timestamptz
}

type ProductionBatch struct {
	ID                   int64
	MadeAt               pgtype.Timestamptz
	RolledBackAt         pgtype.Timestamptz
	IsRolledBack         pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	MadeByPersonID       int64
	RolledBackByPersonID pgtype.Int8
}

type ProductionBatchItem struct {
	ID                      int64
	ProductionBatchID       int64
	MadeForStationJobID     int64
	StationJobID            int64
	BatchRolledBack         bool
	LiveStationJobID        pgtype.Int8
	TransferredStationJobID pgtype.Int8
	CreatedAt               pgtype.Timestamptz
}

type QrCode struct {
	ID            int64
	DiningTableID int64
	Code          string
	IssuedAt      pgtype.Timestamptz
	ReplacedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	PersonID      int64
}

type ReconciledDay struct {
	ID             int64
	SaleDate       pgtype.Date
	PersonID       int64
	CreatedAt      pgtype.Timestamptz
	GapVnd         int64
	GapExplanation pgtype.Text
}

type RecordRevision struct {
	ID              int64
	TargetTableCode string
	TargetRow       int64
	BeforeImage     []byte
	AfterImage      []byte
	Reason          string
	PersonID        int64
	RevisedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type Refund struct {
	ID                   int64
	BillID               pgtype.Int8
	PrepaymentID         pgtype.Int8
	AmountVnd            int64
	MethodCode           string
	SourceMethodCode     pgtype.Text
	Reason               string
	IDIfPrepaymentReturn pgtype.Int8
	BookedAt             pgtype.Timestamptz
	SaleDate             pgtype.Date
	CreatedAt            pgtype.Timestamptz
	PersonID             int64
}

type SalesOrder struct {
	ID                      int64
	ChannelCode             string
	Status                  string
	TableSessionID          pgtype.Int8
	DiningTableID           pgtype.Int8
	CreatedAt               pgtype.Timestamptz
	HandoverCode            pgtype.Text
	IsDoorDelivery          pgtype.Bool
	CustomerPhone           pgtype.Text
	DeliveryAddress         pgtype.Text
	CustomerNeededAt        pgtype.Timestamptz
	CustomerName            pgtype.Text
	ContactNote             pgtype.Text
	SubmissionCode          string
	QrCodeID                pgtype.Int8
	IDIfStandalone          pgtype.Int8
	IDIfCompletedStandalone pgtype.Int8
	IDIfApproved            pgtype.Int8
	IDIfCancelled           pgtype.Int8
}

type ShopBlindSpell struct {
	ID                 int64
	StartedAt          pgtype.Timestamptz
	DeclaredByPersonID pgtype.Int8
	EndedAt            pgtype.Timestamptz
	EndedByPersonID    pgtype.Int8
	CreatedAt          pgtype.Timestamptz
}

type StaffAdvance struct {
	ID               int64
	WorkerPersonID   int64
	AmountVnd        int64
	PaidDate         pgtype.Date
	ApproverPersonID int64
	PersonID         int64
	CreatedAt        pgtype.Timestamptz
}

type StationJob struct {
	ID                   int64
	SalesOrderID         int64
	OrderLineID          pgtype.Int8
	OrderLineComponentID pgtype.Int8
	StationCode          string
	LineQuantity         pgtype.Int4
	ComponentQuantity    pgtype.Int4
	UnitLimit            pgtype.Int4
	Position             int32
	Status               string
	IDIfMadeOrServed     pgtype.Int8
	CreatedAt            pgtype.Timestamptz
}

type StationJobTransfer struct {
	ID                    int64
	ProductionBatchItemID int64
	FromStationJobID      int64
	ToStationJobID        int64
	TransferredAt         pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	PersonID              int64
}

type SupplyDayEntry struct {
	ID             int64
	SupplyItemID   int64
	EntryDate      pgtype.Date
	KindCode       string
	EnteredMeasure pgtype.Numeric
	PersonID       int64
	CreatedAt      pgtype.Timestamptz
}

type SupplyItem struct {
	ID           int64
	Name         string
	PurchaseUnit pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type TableSession struct {
	ID         int64
	Status     string
	IsClosed   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	IDIfClosed pgtype.Int8
}

type TableSessionMember struct {
	ID             int64
	TableSessionID int64
	DiningTableID  int64
	SessionClosed  bool
	CleanedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	PersonID       pgtype.Int8
}

type WrongMakeNote struct {
	ID                  int64
	StationJobID        int64
	SalesOrderID        int64
	LiveStationJobID    pgtype.Int8
	Note                pgtype.Text
	PersonID            int64
	CreatedAt           pgtype.Timestamptz
	CancelledAt         pgtype.Timestamptz
	CancelledByPersonID pgtype.Int8
}
