// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ngung_ban.sql

package sqlcgen

import (
	"context"
)

const ngungBan = `-- name: NgungBan :one
UPDATE menu_item SET discontinued_at = now() WHERE id = $1
RETURNING id, to_char(discontinued_at, 'YYYY-MM-DD"T"HH24:MI:SS.USTZH:TZM') AS discontinued_at
`

type NgungBanRow struct {
	ID             int64
	DiscontinuedAt string
}

// Cửa menu/ngung_ban (P3-06, lớp chu_quan); đã khoá dòng và kiểm mốc trước khi ghi.
func (q *Queries) NgungBan(ctx context.Context, id int64) (NgungBanRow, error) {
	row := q.db.QueryRow(ctx, ngungBan, id)
	var i NgungBanRow
	err := row.Scan(&i.ID, &i.DiscontinuedAt)
	return i, err
}
