// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sua_so_luong.sql

package sqlcgen

import (
	"context"
)

const suaSoLuong = `-- name: SuaSoLuong :one
UPDATE menu_item_component SET quantity = $3 WHERE menu_item_id = $1 AND menu_component_id = $2
RETURNING menu_item_id, menu_component_id, quantity
`

type SuaSoLuongParams struct {
	MenuItemID      int64
	MenuComponentID int64
	Quantity        int32
}

type SuaSoLuongRow struct {
	MenuItemID      int64
	MenuComponentID int64
	Quantity        int32
}

// Cửa menu/sua_thanh_phan (P3-06, lớp chu_quan); chỉ sửa đúng cặp món · thành phần.
func (q *Queries) SuaSoLuong(ctx context.Context, arg SuaSoLuongParams) (SuaSoLuongRow, error) {
	row := q.db.QueryRow(ctx, suaSoLuong, arg.MenuItemID, arg.MenuComponentID, arg.Quantity)
	var i SuaSoLuongRow
	err := row.Scan(&i.MenuItemID, &i.MenuComponentID, &i.Quantity)
	return i, err
}
