// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tim_mon.sql

package sqlcgen

import (
	"context"
)

const timMon = `-- name: TimMon :one
SELECT id FROM menu_item WHERE id = $1
`

// Món có tồn tại không; không có dòng ⇒ menu_item_not_found.
func (q *Queries) TimMon(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, timMon, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
