// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tim_thanh_phan.sql

package sqlcgen

import (
	"context"
)

const timThanhPhan = `-- name: TimThanhPhan :one
SELECT id FROM menu_component WHERE id = $1
`

// Thành phần có tồn tại không; không có dòng ⇒ menu_component_not_found.
func (q *Queries) TimThanhPhan(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, timThanhPhan, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
